(define (problem gripper-x-1)
   (:domain gripper-typed)
   (:objects rooma roomb - room
             ball4 ball3 ball2 ball1 - ball)
   (:init (at-robby rooma rooma)
          (free left left)
          (free right right)
          (at ball4 ball4 rooma)
          (at ball3 ball3 rooma)
          (at ball2 ball2 rooma)
          (at ball1 ball1 rooma))
   (:goal (and (at ball4 ball4 roomb)
               (at ball3 ball3 roomb)
               (at ball2 ball2 roomb)
               (at ball1 ball1 roomb))))