(define (problem gripper-x-7)
   (:domain gripper-typed)
   (:objects rooma roomb - room
             ball16 ball15 ball14 ball13 ball12 ball11 ball10 ball9 ball8
             ball7 ball6 ball5 ball4 ball3 ball2 ball1 - ball)
   (:init (at-robby rooma rooma)
          (free left left)
          (free right right)
          (at ball16 ball16 rooma)
          (at ball15 ball15 rooma)
          (at ball14 ball14 rooma)
          (at ball13 ball13 rooma)
          (at ball12 ball12 rooma)
          (at ball11 ball11 rooma)
          (at ball10 ball10 rooma)
          (at ball9 ball9 rooma)
          (at ball8 ball8 rooma)
          (at ball7 ball7 rooma)
          (at ball6 ball6 rooma)
          (at ball5 ball5 rooma)
          (at ball4 ball4 rooma)
          (at ball3 ball3 rooma)
          (at ball2 ball2 rooma)
          (at ball1 ball1 rooma))
   (:goal (and (at ball16 ball16 roomb)
               (at ball15 ball15 roomb)
               (at ball14 ball14 roomb)
               (at ball13 ball13 roomb)
               (at ball12 ball12 roomb)
               (at ball11 ball11 roomb)
               (at ball10 ball10 roomb)
               (at ball9 ball9 roomb)
               (at ball8 ball8 roomb)
               (at ball7 ball7 roomb)
               (at ball6 ball6 roomb)
               (at ball5 ball5 roomb)
               (at ball4 ball4 roomb)
               (at ball3 ball3 roomb)
               (at ball2 ball2 roomb)
               (at ball1 ball1 roomb))))