(define (problem gripper-x-3)
   (:domain gripper-typed)
   (:objects rooma roomb - room
             ball8 ball7 ball6 ball5 ball4 ball3 ball2 ball1 - ball)
   (:init (at-robby rooma rooma)
          (free left left)
          (free right right)
          (at ball8 ball8 rooma)
          (at ball7 ball7 rooma)
          (at ball6 ball6 rooma)
          (at ball5 ball5 rooma)
          (at ball4 ball4 rooma)
          (at ball3 ball3 rooma)
          (at ball2 ball2 rooma)
          (at ball1 ball1 rooma))
   (:goal (and (at ball8 ball8 roomb)
               (at ball7 ball7 roomb)
               (at ball6 ball6 roomb)
               (at ball5 ball5 roomb)
               (at ball4 ball4 roomb)
               (at ball3 ball3 roomb)
               (at ball2 ball2 roomb)
               (at ball1 ball1 roomb))))