(define (domain barman)
  (:requirements :strips :typing)
  (:types hand level beverage dispenser container - object
  	  ingredient cocktail - beverage
          shot shaker - container)
  (:predicates  (ontable ?dummy - container ?c - container)
                (holding ?dummy - hand ?h - hand ?c - container)
		(handempty ?dummy - hand ?h - hand)
		(empty ?dummy - container ?c - container)
                (contains ?dummy - container ?c - container ?b - beverage)
		(clean ?dummy - container ?c - container)
                (used ?dummy - container ?c - container ?b - beverage)
                (dispenses ?dummy - dispenser ?d - dispenser ?i - ingredient)
		(shaker-empty-level ?dummy - shaker ?s - shaker ?l - level)
		(shaker-level ?dummy - shaker ?s - shaker ?l - level)
		(next ?dummy - level ?l1 ?l2 - level)
		(unshaked ?dummy - shaker ?s - shaker)
		(shaked ?dummy - shaker ?s - shaker)
                (cocktail-part1 ?dummy - cocktail ?c - cocktail ?i - ingredient)
                (cocktail-part2 ?dummy - cocktail ?c - cocktail ?i - ingredient))
		
  (:action grasp
             :parameters (?h - hand ?c - container)
             :precondition (and (ontable ?c ?c) (handempty ?h ?h))
             :effect (and (not (ontable ?c ?c))
	     	     	  (not (handempty ?h ?h))
			  (holding ?h ?h ?c)))

  (:action leave
             :parameters (?h - hand ?c - container)
             :precondition (holding ?h ?h ?c)
             :effect (and (not (holding ?h ?h ?c))
	     	     	  (handempty ?h ?h)
			  (ontable ?c ?c)))
  
  (:action fill-shot
           :parameters (?s - shot ?i - ingredient ?h1 ?h2 - hand ?d - dispenser)
           :precondition (and (holding ?h1 ?h1 ?s)
                              (handempty ?h2 ?h2)
	   		      (dispenses ?d ?d ?i)
                              (empty ?s ?s)
			      (clean ?s ?s))
           :effect (and (not (empty ?s ?s))
	   	   	(contains ?s ?s ?i)
	   	   	(not (clean ?s ?s))
			(used ?s ?s ?i)))


  (:action refill-shot
           :parameters (?s - shot ?i - ingredient ?h1 ?h2 - hand ?d - dispenser)
           :precondition (and (holding ?h1 ?h1 ?s)
                              (handempty ?h2 ?h2)
	   		      (dispenses ?d ?d ?i)
                              (empty ?s ?s)
			      (used ?s ?s ?i))
           :effect (and (not (empty ?s ?s))
                        (contains ?s ?s ?i)))

  (:action empty-shot
           :parameters (?h - hand ?p - shot ?b - beverage)
           :precondition (and (holding ?h ?h ?p)
                              (contains ?p ?p ?b))
           :effect (and (not (contains ?p ?p ?b))
	   	   	(empty ?p ?p)))

  (:action clean-shot
  	   :parameters (?s - shot ?b - beverage ?h1 ?h2 - hand)
           :precondition (and (holding ?h1 ?h1 ?s)
                              (handempty ?h2 ?h2)
			      (empty ?s ?s)
                              (used ?s ?s ?b))
           :effect (and (not (used ?s ?s ?b))
	   	   	(clean ?s ?s)))

  (:action pour-shot-to-clean-shaker
           :parameters (?s - shot ?i - ingredient ?d - shaker ?h1 - hand ?l ?l1 - level)
           :precondition (and (holding ?h1 ?h1 ?s)
			      (contains ?s ?s ?i)
                              (empty ?d ?d)
	   		      (clean ?d ?d)
                              (shaker-level ?d ?d ?l)
                              (next ?l ?l ?l1))
           :effect (and (not (contains ?s ?s ?i))
	   	   	(empty ?s ?s)
			(contains ?d ?d ?i)
                        (not (empty ?d ?d))
			(not (clean ?d ?d))
			(unshaked ?d ?d)
			(not (shaker-level ?d ?d ?l))
			(shaker-level ?d ?d ?l1)))


  (:action pour-shot-to-used-shaker
           :parameters (?s - shot ?i - ingredient ?d - shaker ?h1 - hand ?l ?l1 - level)
           :precondition (and (holding ?h1 ?h1 ?s)
			      (contains ?s ?s ?i)
                              (unshaked ?d ?d)
                              (shaker-level ?d ?d ?l)
                              (next ?l ?l ?l1))
           :effect (and (not (contains ?s ?s ?i))
                        (contains ?d ?d ?i)
	   	   	(empty ?s ?s)
  			(not (shaker-level ?d ?d ?l))
			(shaker-level ?d ?d ?l1)))

  (:action empty-shaker
           :parameters (?h - hand ?s - shaker ?b - cocktail ?l ?l1 - level)
           :precondition (and (holding ?h ?h ?s)
                              (contains ?s ?s ?b)
			      (shaked ?s ?s)
			      (shaker-level ?s ?s ?l)
			      (shaker-empty-level ?s ?s ?l1))
           :effect (and (not (shaked ?s ?s))
	   	   	(not (shaker-level ?s ?s ?l))
	   	   	(shaker-level ?s ?s ?l1)
			(not (contains ?s ?s ?b))
	   	   	(empty ?s ?s)))

  (:action clean-shaker
  	   :parameters (?h1 ?h2 - hand ?s - shaker)
           :precondition (and (holding ?h1 ?h1 ?s)
                              (handempty ?h2 ?h2)
                              (empty ?s ?s))
           :effect (and (clean ?s ?s)))
  
  (:action shake
  	   :parameters (?b - cocktail ?d1 ?d2 - ingredient ?s - shaker ?h1 ?h2 - hand)
           :precondition (and (holding ?h1 ?h1 ?s)
                              (handempty ?h2 ?h2)
			      (contains ?s ?s ?d1)
                              (contains ?s ?s ?d2)
                              (cocktail-part1 ?b ?b ?d1)
			      (cocktail-part2 ?b ?b ?d2)
			      (unshaked ?s ?s))
           :effect (and (not (unshaked ?s ?s))
		        (not (contains ?s ?s ?d1))
                        (not (contains ?s ?s ?d2))
	   	   	(shaked ?s ?s)
                        (contains ?s ?s ?b)))

  (:action pour-shaker-to-shot
           :parameters (?b - beverage ?d - shot ?h - hand ?s - shaker ?l ?l1 - level)
           :precondition (and (holding ?h ?h ?s)
			      (shaked ?s ?s)
			      (empty ?d ?d)
			      (clean ?d ?d)
			      (contains ?s ?s ?b)
                              (shaker-level ?s ?s ?l)
                              (next ?l1 ?l1 ?l))
           :effect (and (not (clean ?d ?d))
	   	   	(not (empty ?d ?d))
			(contains ?d ?d ?b)
			(shaker-level ?s ?s ?l1)
			(not (shaker-level ?s ?s ?l))))
 )