(define (problem prob)
 (:domain barman)
 (:objects 
     shaker1 - shaker
     left right - hand
     shot1 shot2 shot3 shot4 shot5 shot6 shot7 shot8 shot9 shot10 shot11 shot12 shot13 shot14 shot15 - shot
     ingredient1 ingredient2 ingredient3 ingredient4 ingredient5 - ingredient
     cocktail1 cocktail2 cocktail3 cocktail4 cocktail5 cocktail6 cocktail7 cocktail8 cocktail9 cocktail10 cocktail11 - cocktail
     dispenser1 dispenser2 dispenser3 dispenser4 dispenser5 - dispenser
     l0 l1 l2 - level
)
 (:init 
  (ontable shaker1 shaker1)
  (ontable shot1 shot1)
  (ontable shot2 shot2)
  (ontable shot3 shot3)
  (ontable shot4 shot4)
  (ontable shot5 shot5)
  (ontable shot6 shot6)
  (ontable shot7 shot7)
  (ontable shot8 shot8)
  (ontable shot9 shot9)
  (ontable shot10 shot10)
  (ontable shot11 shot11)
  (ontable shot12 shot12)
  (ontable shot13 shot13)
  (ontable shot14 shot14)
  (ontable shot15 shot15)
  (dispenses dispenser1 dispenser1 ingredient1)
  (dispenses dispenser2 dispenser2 ingredient2)
  (dispenses dispenser3 dispenser3 ingredient3)
  (dispenses dispenser4 dispenser4 ingredient4)
  (dispenses dispenser5 dispenser5 ingredient5)
  (clean shaker1 shaker1)
  (clean shot1 shot1)
  (clean shot2 shot2)
  (clean shot3 shot3)
  (clean shot4 shot4)
  (clean shot5 shot5)
  (clean shot6 shot6)
  (clean shot7 shot7)
  (clean shot8 shot8)
  (clean shot9 shot9)
  (clean shot10 shot10)
  (clean shot11 shot11)
  (clean shot12 shot12)
  (clean shot13 shot13)
  (clean shot14 shot14)
  (clean shot15 shot15)
  (empty shaker1 shaker1)
  (empty shot1 shot1)
  (empty shot2 shot2)
  (empty shot3 shot3)
  (empty shot4 shot4)
  (empty shot5 shot5)
  (empty shot6 shot6)
  (empty shot7 shot7)
  (empty shot8 shot8)
  (empty shot9 shot9)
  (empty shot10 shot10)
  (empty shot11 shot11)
  (empty shot12 shot12)
  (empty shot13 shot13)
  (empty shot14 shot14)
  (empty shot15 shot15)
  (handempty left left)
  (handempty right right)
  (shaker-empty-level shaker1 shaker1 l0)
  (shaker-level shaker1 shaker1 l0)
  (next l0 l0 l1)
  (next l1 l1 l2)
  (cocktail-part1 cocktail1 cocktail1 ingredient3)
  (cocktail-part2 cocktail1 cocktail1 ingredient1)
  (cocktail-part1 cocktail2 cocktail2 ingredient4)
  (cocktail-part2 cocktail2 cocktail2 ingredient3)
  (cocktail-part1 cocktail3 cocktail3 ingredient2)
  (cocktail-part2 cocktail3 cocktail3 ingredient5)
  (cocktail-part1 cocktail4 cocktail4 ingredient2)
  (cocktail-part2 cocktail4 cocktail4 ingredient5)
  (cocktail-part1 cocktail5 cocktail5 ingredient3)
  (cocktail-part2 cocktail5 cocktail5 ingredient2)
  (cocktail-part1 cocktail6 cocktail6 ingredient4)
  (cocktail-part2 cocktail6 cocktail6 ingredient2)
  (cocktail-part1 cocktail7 cocktail7 ingredient4)
  (cocktail-part2 cocktail7 cocktail7 ingredient1)
  (cocktail-part1 cocktail8 cocktail8 ingredient2)
  (cocktail-part2 cocktail8 cocktail8 ingredient3)
  (cocktail-part1 cocktail9 cocktail9 ingredient5)
  (cocktail-part2 cocktail9 cocktail9 ingredient3)
  (cocktail-part1 cocktail10 cocktail10 ingredient5)
  (cocktail-part2 cocktail10 cocktail10 ingredient2)
  (cocktail-part1 cocktail11 cocktail11 ingredient5)
  (cocktail-part2 cocktail11 cocktail11 ingredient4)
)
 (:goal
  (and
     (contains shot1 shot1 cocktail3)
     (contains shot2 shot2 cocktail7)
     (contains shot3 shot3 cocktail1)
     (contains shot4 shot4 cocktail6)
     (contains shot5 shot5 cocktail4)
     (contains shot6 shot6 cocktail10)
     (contains shot7 shot7 cocktail9)
     (contains shot8 shot8 cocktail8)
     (contains shot9 shot9 cocktail5)
     (contains shot10 shot10 cocktail11)
     (contains shot11 shot11 cocktail2)
     (contains shot12 shot12 ingredient1)
     (contains shot13 shot13 ingredient4)
     (contains shot14 shot14 ingredient2)
)))
