(define (problem BLOCKS-15-0)
(:domain BLOCKS)
(:objects A C L D J H K O N G I F B M E - block)
(:INIT (CLEAR E E) (CLEAR M M) (CLEAR B B) (CLEAR F F) (CLEAR I I) (ONTABLE G G)
 (ONTABLE N N) (ONTABLE O O) (ONTABLE K K) (ONTABLE H H) (ON E E J) (ON J J D) (ON D D L)
 (ON L L C) (ON C C G) (ON M M N) (ON B B A) (ON A A O) (ON F F K) (ON I I H) (HANDEMPTY))
(:goal (AND (ON G G O) (ON O O H) (ON H H K) (ON K K M) (ON M M F) (ON F F E) (ON E E A)
            (ON A A B) (ON B B L) (ON L L J) (ON J J D) (ON D D N) (ON N N I) (ON I I C)))
)